language: android
android:
  components:
    - android-23
    - build-tools-23.0.0
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21

before_script:
  - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"
script: "./gradlew clean build test -Dpre-dex=false"
branches:
  only:
  - master